// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCALNvP3VfthL9c2Ng0iz9oqEM2oD2giOE',
    appId: '1:234150718407:web:66ae2a033a8818f22987e2',
    messagingSenderId: '234150718407',
    projectId: 'fame-nadz',
    authDomain: 'fame-nadz.firebaseapp.com',
    storageBucket: 'fame-nadz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhvoOI6uS1PVailqKfx4PMEVAKBv7zLo',
    appId: '1:234150718407:android:4a8c5f75eac914bb2987e2',
    messagingSenderId: '234150718407',
    projectId: 'fame-nadz',
    storageBucket: 'fame-nadz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusUQkEgovQpq9-j-kmd1_LpKw2mZ4goY',
    appId: '1:234150718407:ios:88431f7073c413cb2987e2',
    messagingSenderId: '234150718407',
    projectId: 'fame-nadz',
    storageBucket: 'fame-nadz.appspot.com',
    iosBundleId: 'com.nadz.fameNadz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCusUQkEgovQpq9-j-kmd1_LpKw2mZ4goY',
    appId: '1:234150718407:ios:35ca950fee66fb212987e2',
    messagingSenderId: '234150718407',
    projectId: 'fame-nadz',
    storageBucket: 'fame-nadz.appspot.com',
    iosBundleId: 'com.nadz.fameNadz.RunnerTests',
  );
}
